Airsoft/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from news.urls import *
from users.urls import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # path('', include('ui.urls')),
    # path('api/', include('api.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", WakeUp.as_view(), name="api_entrypoint"),
    path("test", TestData.as_view(), name="api_entrypoint"),
    path("allowlist", AllowList.as_view(), name="api_allowList"),
    path("data", GetData.as_view(), name="api_getdata"),
]

events/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeEvents.as_view(), name='events_home'),
    path('user-events/', HomeEvents.as_view(), name='user_events_list'),
    path('event/<int:pk>/', ViewEvents.as_view(), name='view_events'),

    path('event/<int:pk>/user-table',  EventUsersList.as_view(), name='view_event_users'),

    path('event/register/<int:pk_event>/reg', register_event, name='events_register'),  # регистрация игрока на игру
    path('event/register/<int:pk_event>/cancel', register_cancel_visit, name='events_cancelVisit'),  # Отметить неявку на игру. В get должен быть id пользователя

    # Для получения данных
    path('event/<int:pk>/users-list', EventUsersListTest.as_view(), name='view_event_users_data'),  # Список пользователь на меро

    # path('event/register/allowlist', AllowList.as_view(), name='api_allowList'),
    # path('event/register/data', GetData.as_view(), name='api_getdata')
]

events/models.py
from django.db import models
from django.urls import reverse
import datetime
from django.utils import timezone


# TODO подумать, как к меро можно закрепить альбом
class Event(models.Model):
    """Описывает мероприятия команды"""

    def __str__(self):
        return self.name

    name = models.CharField(max_length=128, verbose_name='Название')
    content = models.TextField(verbose_name='Описание мероприятия', blank=True, null=True)
    price = models.IntegerField(verbose_name='Стоимость', blank=True, null=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    is_active = models.BooleanField(default=True, verbose_name='Активно')  # меняется при истечении срока

    location_description = models.CharField(max_length=128, verbose_name='Место проведения', blank=True, null=True)
    location_coord = models.CharField(max_length=128, verbose_name='Координаты', blank=True, null=True)
    meeting_point = models.CharField(max_length=128, verbose_name='Точка сбора', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    close_reg_at = models.DateTimeField(verbose_name='Окончание регистрации', blank=True, null=True)
    starting_at = models.DateTimeField(verbose_name='Начало мероприятия', blank=True, null=True)

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('view_events', kwargs={'pk': self.pk})

    @property
    def reg_is_over(self):
        if self.close_reg_at is not None:
            return timezone.now() > self.close_reg_at
        return False

    @property
    def event_is_over(self):
        if self.starting_at is not None:
            return timezone.now() > self.starting_at
        return False



class UserEvent(models.Model):
    """
    Связывает игрока с мероприятием

    Можно отследить где был и что делал.
    После каждого меро можно дать характеристику конкретно для этого игрока

    """
    def __str__(self):
        return self.event.name

    USER_STATUSES = (
        (0, 'Зарегистрировался'),
        (1, 'Отменил регистрацию'),  # Ранее да, но потом отказался. Указал причину
        (2, 'Отказался'),            # С указанием причины
        (3, 'Игнорировал'),          # Ставится по умолчанию для тех, кто не голосовал после завершения меро
        (4, 'Не явился'),            # Зареган, но не приехал. Проставляется командиром
    )
    USER_PAYMENT_STATUS = (
        (False, 'Не оплачено'),
        (True, 'Оплачено'),
    )

    # user будет доступен по свзи MtM
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    user_status = models.IntegerField(default=0, choices=USER_STATUSES, verbose_name='Статус регистрации')
    user_payment = models.BooleanField(default=False, verbose_name='Статус оплаты', choices=USER_PAYMENT_STATUS)
    visited = models.BooleanField(default=False, verbose_name='Посещение')

    user_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий игрока')
    leader_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')

    class Meta:
        verbose_name = 'Пользователь-Мероприятие'
        verbose_name_plural = 'Пользователь-Мероприятия'

    # @classmethod
    # def userstatus_choise(self, ):

events/forms.py
# from django import forms
# from django.core.exceptions import ValidationError
#
# from .models import Event
#
#
# class EventForm(forms.ModelForm):
#     class Meta:
#         model = Event
#         # fields = '__all__' использование всех полей
#         fields = ['name',
#                   'description',
#                   'is_published',
#                   'is_active',
#                   'price',
#                   'location_description',
#                   'location_coord',
#                   'meeting_point',
#                   'starting_at',
#                   'close_reg_at'
#                   ]
#
#         # widgets = {
#         #     'title': forms.TextInput(attrs={'class': 'form-control'}),
#         #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
#         #     'category': forms.Select(attrs={'class': 'form-control'})
#         # }

events/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    View,
    TemplateView,
)

# from django.http import HttpResponseRedirect
from django.http import HttpResponse
from os.path import join as osjoin, exists
from os import getcwd

# from django.http import JsonResponse
# from django.core import serializers

import json
from django.core.serializers.json import DjangoJSONEncoder

from .models import Event, UserEvent
from users.models import User


# from django.contrib.auth.forms import UserCreationForm если бы не юзали свою форму
CONF_FILE = osjoin(getcwd(), f"events\\files\\tables.json")


class HomeEvents(ListView, LoginRequiredMixin):
    """Для просмотра списка игр"""

    model = Event
    template_name = "events/events_list.html"
    context_object_name = "events"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Мероприятия"
        return context

    def get_queryset(self):
        if "user-events" in str(self.request):
            # Только те, на которые зареган текущий пользователь

            return Event.objects.filter(
                pk__in=self.request.user.profile.events.all().values_list(
                    "event", flat=True
                ),
                userevent__user_status=0,
                userevent__user=self.request.user.profile,
            )
        return Event.objects.filter(is_published=True)


class ViewEvents(DetailView):
    """Для просмотра конкретной игры"""

    model = Event
    context_object_name = "event_item"

    def get_object(self, queryset=None):
        obj = super(ViewEvents, self).get_object(queryset=queryset)
        self.set_missed(obj)
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_is_registered"] = False
        context["user_event"] = None
        context["users_count"] = UserEvent.objects.filter(
            event=context["object"], user_status=0
        ).count()

        if self.request.user.is_authenticated is False:
            return context

        user_event = self.request.user.profile.events.filter(event=context["object"])
        if user_event.count() != 0:
            context["user_event"] = user_event[0]
        return context

    def set_missed(self, event_obj):
        """Задать неявку для всех остальных пользователей"""
        # 0) Проверить, текущая дата больше даты окончания мероприятия
        # 1) Получить список пользователей, которые не зарегались сюда
        # 2) Пройтись по этому списку и создать для каждого юзер-ивент запись
        # 2.2) Сохранять

        # только те, что уже    имеют обьект регистрации на игру
        if event_obj.event_is_over:
            pass

        event_registrations = UserEvent.objects.filter(event=event_obj)
        users_list = User.objects.filter(profile__events__in=event_registrations)

        # TODO вызывает ошибку, тк не поддерживается MySQL
        # truants = User.objects.all().difference(users_list)
        truants = User.objects.all().exclude(id__in=users_list)

        # TODO баг при нескольких вызовах подряд
        user_comment = "Автопрогул. Работа сервера"
        for user in truants:
            try:
                tmp, created = UserEvent.objects.filter(
                    user=user.profile
                ).get_or_create(
                    event=event_obj, user_status=3, user_comment=user_comment
                )
                if created:
                    tmp.user.add(user.profile)
            except Exception as err:
                pass


def register_event(request, *args, **kwargs):
    """Для регистрации на игру

        USER_STATUSES = (
        (0, 'Зарегистрировался'),
        (1, 'Отменил регистрацию'),  # Ранее да, но потом отказался. Указал причину
        (2, 'Отказался'),            # С указанием причины
        (3, 'Игнорировал'),          # Ставится по умолчанию для тех, кто не голосовал после завершения меро
        (4, 'Не явился'),            # Зареган, но не приехал. Проставляется командиром
    )
    """
    model = UserEvent
    user_comment = None

    if request.method == "POST":
        try:
            user_comment = json.loads(request.body).get("user_comment", None)
        except Exception as err:
            user_comment = "Server side error"

    pk = kwargs.get("pk_event")
    obj, created = model.objects.filter(
        event_id=pk, user=request.user.profile
    ).get_or_create(event_id=pk)

    if created:
        obj.user.add(request.user.profile)
        obj.user_status = 2 if request.method == "POST" else 0
        obj.user_comment = user_comment
        obj.save()
    else:
        # Сначала отказался, а потом передумал
        obj.user_status = 2 if request.method == "POST" else 0
        obj.user_comment = user_comment
        obj.save()
    return redirect("view_events", pk)


# При отмене регистрации обьект с регистрацией не удаляется, а изменяется статус user_status на 1 или 2 (отказался)
@login_required
def register_cancel_visit(request, *args, **kwargs):
    """Отмена/изменение регистрации на игру
    pk_event ключ на событие, а в get параметрах передать id регистрации
    """
    response = {"stateside": 200}

    pk_reg = request.GET.get("reg_id", None)
    if pk_reg:
        user_event = UserEvent.objects.get(pk=pk_reg)
        if user_event.user_status == 0:
            user_event.user_status = 4  # неявился
            user_event.visited = False
            user_event.user_comment = "Неявка. Командир группы"
            user_event.save()
        else:
            user_event.user_status = 0  # зарегистрировался
            user_event.visited = True
            user_event.user_comment = ""
            user_event.save()
    return HttpResponse(
        json.dumps(response, cls=DjangoJSONEncoder), content_type="application/json"
    )


class EventUsersList(View):
    """Таблица пользователей связанных с мероприятием"""

    context = {}
    template_name = "events/users_on_event.html"
    extra_template_name = "events/users_on_event_check.html"
    cancel_table = False

    def get(self, request, *args, **kwargs):
        # ожидаемый параметр, для открытия таблицы с возможностью подтверждать регистрацию
        template_name = (
            self.template_name
            if not request.GET.get("cancel_table", None)
            else self.extra_template_name
        )
        self.context["title"] = "Список участников"
        self.context["event_pk"] = self.kwargs.get("pk")
        return render(request, template_name, self.context)


class EventUsersListTest(LoginRequiredMixin, View):
    """Контролер для полоучения табличных данных формата json
    работает со списком заререстрировавшихся на игру пользователей
    """

    model = UserEvent
    user_statuses = dict((k, v) for k, v in model.USER_STATUSES)

    def get(self, request, pk):
        response = {}
        # pk - индекс мероприятия
        # data = self.model.objects.filter(event_id=pk)
        # user = auth.get_user(request)

        request_filter = request.GET.get(
            "filter_patt", None
        )  # будет набор заготовленных фильтров
        # cancelTable - только те, что отметились, что едут на игру

        user_groups = request.user.groups.values_list("name", flat=True)
        is_leader = "GroupLeaders" in user_groups

        qs_filter = {"event_id": pk}

        if request_filter == "cancelTable":
            qs_filter["user_status__in"] = [0, 4]

        # Для обычных бойцов показывать только тех, кто едет на игру
        if not is_leader:
            qs_filter["user_status"] = 0

        data = list(
            self.model.objects.filter(**qs_filter).values(
                "pk",
                "user_status",
                "user_comment",
                "visited",
                "user__user",
                "user__team_alias",
                "user__user__first_name",
                "user__user__last_name",
            )
        )

        for row in data:
            # if not is_leader and row['user_status'] != 0:
            #     continue
            row["user_name"] = "{} {}".format(
                row["user__user__last_name"], row["user__user__first_name"]
            )  # qs_json = serializers.serialize('json', data)  # нельзя использовать, есл указывать какие поля нужно получить
            row["user_pk"] = row.pop("user__user")
            row["user_event_pk"] = row.pop("pk")
            row["user_status_code"] = row["user_status"]
            row["user_status"] = self.user_statuses.get(row["user_status"], "Error")
            row["user_team_alias"] = row["user__team_alias"]

            row.pop("user__team_alias")
            row.pop("user__user__first_name")
            row.pop("user__user__last_name")

        response["Data"] = data
        response["Columns"] = [
            {
                "name": "user_name",
                "displayName": "Пользователь",
                "search": 1,
                "sort": 1,
                "width": "",
            },
            {
                "name": "user_team_alias",
                "displayName": "Позывной",
                "search": 1,
                "sort": 1,
                "width": "",
            },
            {
                "name": "user_status",
                "displayName": "Статус регистрации",
                "search": 0,
                "sort": 1,
                "width": "",
            },
        ]

        # Для лидера группы показывать статус регистрации игрока и его комент
        if is_leader and not request_filter == "cancelTable":
            response["Columns"].append(
                {
                    "name": "user_comment",

events/templates/events/UserEvent_detail.html
{% extends 'base.html' %}

{#event#}
{#user_status#}
{#user_payment#}
{#visited#}
{#user_comment#}
{#leader_comment#}

{% block content %}
    <div class="container py-sm-3">
        <div class="row justify-content-center text-light my-3">
            <div class="col-md-10 bg-dark my-2 ">
                <div class="row">
                    <div class="col-md-8 py-2">
                        <h3>{{ event_item.event.name }}</h3>
                        <p>{{ event_item.user_status }}</p>user_status
                    </div>

{#                    <div class="col-md-4 py-2" style="background: #292929">#}
{#                        <div class="row py-2">#}
                            {#                            <div class="col-md-4">Начало</div>#}
{#                            <div class="col"><h4>{{ event_item.starting_at }}</h4></div>#}
{#                        </div>#}
{#                        <div class="row py-2">#}
{#                            <div class="col-md-4">Стоимость</div>#}
{#                            <div class="col">{{ event_item.price|default_if_none:"Бесплатно" }}</div>#}
{#                        </div>#}
{#                        <div class="row py-2">#}
{#                            <div class="col-md-4">Место проведения</div>#}
{#                            <div class="col">{{ event_item.location_description }}</div>#}
{#                        </div>#}
{#                        <div class="row py-2">#}
{#                            <div class="col-md-4">Окончание регистрации</div>#}
{#                            <div class="col">{{ event_item.close_reg_at }}</div>#}
{#                        </div>#}
{#                        <div class="row py-2">#}
{#                            <div class="col">#}
{#                                Отменить регистарцию, если пользователь уже зареган на игру. #}
{##}
{#                                <a href="#" class="btn btn-primary stretched-link" style="width: 100%">Я пойду</a>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% load event_users %}

{% block content %}
    {{ event_item.pk|json_script:"event_id" }}
    {% url 'events_register' event_item.pk as events_register_url %}
    {{ events_register_url|json_script:"events_register_url" }}

{#    <div class="row py-2">#}
{#        <a href="{% url 'view_event_users' event_item.pk %}?cancel_table=true"#}
{#           class="btn btn-primary stretched-link"#}
{#           style="width: 100%;"#}
{#        >#}
{#            Подтвердить присутсвие#}
{#        </a>#}
{#    </div>#}


    <div class="container py-sm-3">
        <div class="row justify-content-center text-light my-3">
            <div class="col-md-10 bg-dark my-2 ">
                <div class="row">
                    <div class="col-md-8 py-2">
                        <h3>{{ event_item.name }}</h3>

                        {% autoescape off %}
                            <p class="card-text">{{ event_item.content | linebreaks }}</p>
                        {% endautoescape %}
                    </div>

                    <div class="col-md-4 py-2" style="background: #292929">
                        <div class="row py-2">
                            <div class="col"><h4>{{ event_item.starting_at|default_if_none:"---" }}</h4></div>
                        </div>
                        {% if  event_item.event_is_over %}
                            <div class="row py-2">
                                <div class="col"><h4>Мероприятие окончено</h4></div>
                            </div>
                        {% endif %}
                        <div class="row py-2">
                            <div class="col-md-4">Стоимость</div>
                            <div class="col">{{ event_item.price|default_if_none:"Бесплатно" }}</div>
                        </div>
                        <div class="row py-2">
                            <div class="col-md-4">Место проведения</div>
                            <div class="col">{{ event_item.location_description|default_if_none:"---" }}</div>
                        </div>
                        <div class="row py-2">
                            <div class="col-md-4">Окончание регистрации</div>
                            <div class="col">{{ event_item.close_reg_at|default_if_none:"---" }}</div>
                        </div>
                        <div class="row py-2">
                            <div class="col-md-4">Участвуют</div>
                            <div class="col">{{ users_count }} игроков</div>
                        </div>
                        <div class="row py-2">


                            {% comment %} Блок с кнопкой регистрации на игру  {% endcomment %}
                            <div class="col">


                                {% if event_item.reg_is_over or event_item.event_is_over %}

                                    <div class="py-2">
                                        <div class="reg-closed btn"
                                             style="width: 100%;">
                                            Регистрация завершена
                                        </div>
                                    </div>

                                    {% comment %} После меро можно отметить присутсвующих  {% endcomment %}
                                    {% if request.user|has_group:"GroupLeaders" %}
                                        <div class="py-2">
                                            <button class="btn btn-primary" style="width: 100%;"
                                                    onclick="window.open(`{% url 'view_event_users' event_item.pk %}?cancel_table=true`, `_blank`)">
                                                Подтвердить присутсвие
                                            </button>
                                        </div>
                                    {% endif %}

                                {% else %}
                                    {% if request.user.is_authenticated %}
                                        {% if user_event.user_status == 0 %}

                                            <a href="javascript:addTextField()"
                                               class="reg-refuse btn stretched-link"
                                               style="width: 100%">Отменить
                                                регистрацию</a>

                                        {% else %}

                                            <div class="row py-2">
                                                <div class="{% if user_event == None %}col-8 {% else %} col {% endif %}">
                                                    <a href="{% url 'events_register' event_item.pk %}"
                                                       class="btn btn-primary stretched-link" style="width: 100%">Я пойду</a>
                                                </div>
                                                {% if user_event == None %}
                                                    <div class="col">
                                                        <a href="javascript:addTextField();"
                                                           class="reg-refuse btn stretched-link" style="width: 100%">Не еду</a>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                            </div>


                        </div>

{#                        <div class="row-py-2">#}
{#                            <div class="col">#}
{#                                <div class="form-group">#}
{#                                    <label for="exampleFormControlTextarea1">Указание причины</label>#}
{#                                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}


                        {% comment %} Блок с зарегистрированными пользователями {% endcomment %}

                        {% get_event_users user event_item.pk as reg_users %}
                        {% if reg_users.count > 0 %}
                            <a href="{% url 'view_event_users' event_item.pk %}" target="_blank">Список игроков:</a>
                            <div class="row py-2">
                                <div class="col">
                                    <div class="row row-cols-3 text-center">

                                        {% for reg_user in reg_users %}
                                            <div class="col">

                                                {% if reg_user.profile.photo %}
                                                    <img src="https://w7.pngwing.com/pngs/633/817/png-transparent-computer-icons-military-soldier-military-backpack-swat-soldier-police-thumbnail.png"
                                                         alt="Avatar" class="avatar mb-1">
                                                {% else %}
                                                    <img src="https://cdn1.iconfinder.com/data/icons/society-profession-avatar/1024/Society_Profession_Avatar_I-03-512.png"
                                                         alt="Avatar" class="avatar mb-1">

                                                {% endif %}
{#                                                {% if reg_user.profile.team_alias %}#}
{#                                                    <p>{{ reg_user.profile.team_alias }}</p>#}
{#                                                {% else %}#}
                                                    <p>{{ reg_user.first_name }} {{ reg_user.last_name }}</p>
{#                                                {% endif %}#}
                                            </div>

                                        {% endfor %}

                                    </div>
                                </div>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block javascript %}
    <script src="{% static 'js/events/events_comment.js' %}"></script>
{% endblock %}

events/templates/events/events_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="container py-sm-3">
        {% if events.count < 1 %}
            <h4 class="text-center">Список мероприятий пуст</h4>
        {% endif %}

        <div class="row justify-content-center text-light">
            {% for event in events %}
                <div class="col-md-10 bg-dark pt-3 pb-1 my-2 ">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>{{ event.name }}</h4>
                            <p>Опубликовано: {{ event.created_at }}</p>
                        </div>

                        <div class="col-md-2 d-none d-md-block text-center">
                            {% if event.starting_at %}
                                <h4>{{ event.starting_at|date:"d.m.Y" }}</h4>
                            {% endif %}
                        </div>
                        <div class="col-md-2 d-none d-block d-md-none">
                            {% if event.starting_at %}
                                <h4>{{ event.starting_at|date:"d.m.Y" }}</h4>
                            {% endif %}
                        </div>


                        <div class="col-md-2 d-none d-md-block text-center">
                            <a href="{{ event.get_absolute_url }}">Открыть</a>
                        </div>
                        <div class="col-md-2 d-none d-block d-md-none">
                            <a href="{{ event.get_absolute_url }}">Открыть</a>
                        </div>
                        <a href="{{ event.get_absolute_url }}" class="stretched-link"></a>
                    </div>
                </div>
            {% endfor %}
        </div>


        <div class="row justify-content-center text-light">
            <div class="col-md-10 pt-3 pb-1 my-2 ">
                {% include 'inc/_paginator.html' %}
            </div>
        </div>
    </div>



{% endblock %}

events/templates/events/users_on_event_static.html
{% extends 'base.html' %}
{% load event_users %}

{% block content %}
    <div class="awards_table">
        <div class="table-responsive" style="overflow-x:hidden;">
            <table class="table mb-0">
                <thead>
                <tr>
                    <th class="name_colunm_awards">Пользователь</th>
                    <th class="descr_colunm_awards">Позывной</th>
                    <th class="descr_colunm_awards">Статус</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                    {% get_detail_userreg item event_pk as userevent_data %}
                    <tr>
                        <td>{{ item.last_name }} {{ item.first_name }}</td>
                        <td>{{ item.profile.team_alias|default_if_none:"---" }}</td>
                        <td>{{ userevent_data.get_user_status_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}